### ISSUE TITLE
Possible successor for QRXfer

### ISSUE THREAD

**Issue by DonaldTsang** [leonjza/qrxfer#2]
TxQR looks and feels more streamlined than QRXfer, maybe take a look at that?
- https://github.com/divan/txqr
- https://github.com/divan/txqr-reader
- https://github.com/ThePlasmaRailgun/TXQR-Android

**Comment by leonjza** [comment]
Awesome! 👍 
Happy to include a link that project in the README. PR's welcome!

**Comment by DonaldTsang** [comment]
@leonjza Ideas:
1. Use fountain/tornado/raptor codes for the QR code
2. Use of ANSI code to make sure the QR code always stay in one place
  - http://tldp.org/HOWTO/Bash-Prompt-HOWTO/x361.html
  - http://www.lihaoyi.com/post/BuildyourownCommandLinewithANSIescapecodes.html
